spring:
    application:
        name: drive-api
    datasource:
        type: com.zaxxer.hikari.HikariDataSource # HikariCP is the default connection pool in Spring Boot
        driver-class-name: org.postgresql.Driver # PostgreSQL driver
        url: jdbc:postgresql://localhost:5432/all_in_one?useSSL=false
        username: postgres
        password: postgres

server:
    port: 8888
logging:
    level:
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type: TRACE
